spring.application.name=oaut2

# El fragmento "google" es el registrationId. Spring construye la URL de
# callback automaticamente: /login/oauth2/code/google
spring.security.oauth2.client.registration.google.client-id=583273421541-n7hj5ohcdlulc4m2ujkrmbdg302ovm2m.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# scope define que informacion del usuario solicitamos a Google.
# openid: activa OIDC y garantiza un ID Token estandar.
# profile: nombre, foto. email: direccion de correo.
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
